### ISSUE TITLE
File not found issue when doing fx plan initialize

### ISSUE THREAD

**Issue by ghost** [intel/openfl#107]
Hi there,

I was trying to do `fx plan initialize ` but encountered some error message with the data loader as follows:

```
fx workspace create --prefix ${HOME}/2dunet --template tf_2dunet
pip install -r requirments.txt
fx plan initialize
FileNotFoundError: [Errno 2] No such file or directory: "'/raid/datasets/BraTS17/by_institution_NIfTY/1'"
```

Nevertheless, we also tried with files and directories that are valid and must exist there such as '/home/', but the error massage is still there, saying `No such file or directory: "'/home/'"`

**Comment by itrushkin** [comment]
@xjustintongx Thank you for your interest in the project!
Do you have BraTS17 dataset locally? This is the only workspace template that requires users to obtain the data because of legal constraints.
If you do have it:
1) Try removing quotes from your path inside YAML, perhaps it'll help. E. g.: `/home/user/BraTS17` instead of `'/home/user/BraTS17'`
2) Try following steps in #99.

**Comment by alexey-gruzdev** [comment]
@xjustintongx Could you please confirm that issue still unresolved? and I wonder, if you have time to double-check what @itrushkin has suggested?

**Comment by ghost** [comment]
> @xjustintongx Could you please confirm that issue still unresolved? and I wonder, if you have time to double-check what @itrushkin has suggested?

Thanks for reminding me. We tried the suggestions of @itrushkin a while ago, but the problem still exists. 

The template workspace _tf_2dunet_ seems to be the only workspace that we saw these errors. The others worked out fine.

Currently, I am no longer working on the same project. I am sorry that I can not provide further details. 

Thanks for the help!
