### ISSUE TITLE
Client training performance of a container always better than others

### ISSUE THREAD

**Issue by mimmose** [intel/openfl#118]
I'm a student and trying to understand this FL framework. I've started with notebook tutorials, like the one called "_new_python_api_Tensorflow_MNIST.ipynb_".  I've run the scenario with 2 collaborators, each one in a respective container. I noticed that a collaborator always (more than 10 run) has better accuracy metrics better than another one even if:
- the collaborators both have the same performance (ram, cpus, etc);
- there is a shuffle of mnist dataset elements and the do_sharding method which assigns different portions of the whole dataset to clients;
-  the collaborators both uses the same model.

Could this be a feature of this FL framework that I don't know or maybe I haven't understand well how the learning phases works? Thanks for your patience and support.

**Comment by alexey-gruzdev** [comment]
@mimmose Hi! Thanks for the interest in OpenFL!:)
Generally speaking, it's a strange behavior and by design it should not be working like you are describing.

Let me clarify each of the points:
* >  the collaborators both have the same performance (ram, cpus, etc);

This should not affect accuracy, it should affect training time on each respective collaborator

* > there is a shuffle of mnist dataset elements and the `do_sharding()` method which assigns different portions of the whole dataset to clients;

In case of 2 collaborators, `do_sharding()` method should assign half of the data on one collaborator & other half to the second collaborator. 

* > the collaborators both uses the same model.

That's by design, in case if you have different model architecture it's not clear how to do aggregation. However, it should not affect the problem you are describing.

I would suggest to try [PyTorch example](https://github.com/intel/openfl/tree/develop/openfl-tutorials/interactive_api_tutorials_(experimental)/Pytorch_Kvasir_UNET_workspace) and see if you get the same effect. Also, you could try to change `do_sharding()` method and assign to collaborator 1 significantly more data and then expect it to perform much better. After that, you could repeat this for collaborator 2 and effect should be transferred to it. 

And please let us know if after that you still see the same behavior - so we could investigate this further.:)

**Comment by mimmose** [comment]
@alexey-gruzdev thanks for your answer. I've tried to change the shuffle function adding the code as in figure (between the "added" label). I figured out it was more a problem in the shuffle method. I don't know why.

![canc](https://user-images.githubusercontent.com/50296295/124954310-3b13fc80-e016-11eb-88c2-2f2af7d11377.png)

**Comment by alexey-gruzdev** [comment]
@mimmose okay, sounds like it resolved. I'm happy that you figure out this.
