### ISSUE TITLE
Provide write access to TensorDB through AggregationFunctionInterface

### ISSUE THREAD

**Issue by psfoley** [intel/openfl#131]
Recently, OpenFL has expanded the types of custom aggregation functions that can be computed on collaborator models. Some participants from the FeTS Challenge had complex aggregation strategies they wished to implement that were based on [novel calculated metrics](https://github.com/FETS-AI/Challenge/discussions/59) that could be used for a future round.

**Comment by itrushkin** [comment]
As a workaround, one can store calculated values in class properties and update them every round. I wouldn't recommend providing full access to TensorDB since we have internal entities dependant on its contents: we deal with certain tags on different stages of communication between aggregator and collaborator. Errors users may receive in case of inconsistent DB state may be confusing.

**Comment by psfoley** [comment]
Closed via https://github.com/intel/openfl/pull/417
