### ISSUE TITLE
An error occurs when 'collaborator.settings.delta_updates' set to 'True'

### ISSUE THREAD

**Issue by siyuqqq** [intel/openfl#269]
**Describe the bug**
Hi OpenFL team,
I try to train my model based on the 'default' workspace. I override the value of 'collaborator.settings.delta_updates' to 'True' in the plan.  An error occurs at the beginning of the second round: "AttributeError: 'tuple' object has no attribute 'remove'".

I've also tried to change this value in "Federated_Keras_MNIST_Tutorial" and got the same error. But everything is OK when I change this value back to 'False'.

Could you help me out to resolve the issue?

**Screenshots**
<img width="1184" alt="bug" src="https://user-images.githubusercontent.com/29030361/146119894-a1bb987d-5e6f-4b5d-931a-ac834620926b.png">

**Desktop (please
 complete the following information):**
 - OS: ubuntu 20.04.2.0
 - Browser Firefox

**Comment by alexey-gruzdev** [comment]
Hi @Siyuqqq ! Thanks for you interest in OpenFL and reaching out to us!

Yeah, we know, that such bug exists, and for right now we don't have resolution for this issue yet.

In general, we would recommend to use [interactive_api examples](https://github.com/intel/openfl/tree/develop/openfl-tutorials/interactive_api), since they rely on Director-based workflow which is preferred. You can read more about intentions behind this approach in the [Go Federated blog](https://towardsdatascience.com/go-federated-with-openfl-8bc145a5ead1). It's not tested with `delta_updates=True`, it's fair to assume that it could work incorrectly. However, it would be good experience, if you plan to work with OpenFL further.

**Comment by siyuqqq** [comment]
> Hi @Siyuqqq ! Thanks for you interest in OpenFL and reaching out to us!
> 
> Yeah, we know, that such bug exists, and for right now we don't have resolution for this issue yet.
> 
> In general, we would recommend to use [interactive_api examples](https://github.com/intel/openfl/tree/develop/openfl-tutorials/interactive_api), since they rely on Director-based workflow which is preferred. You can read more about intentions behind this approach in the [Go Federated blog](https://towardsdatascience.com/go-federated-with-openfl-8bc145a5ead1). It's not tested with `delta_updates=True`, it's fair to assume that it could work incorrectly. However, it would be good experience, if you plan to work with OpenFL further.

Hi @alexey-gruzdev,

Thanks for your advice. I'll try out the interactive_api examples.

**Comment by psfoley** [comment]
Hi @Siyuqqq, thanks a lot for bringing visibility to this! 

I just submitted a fix to the problem in [this PR](https://github.com/intel/openfl/pull/279). There was a small bug in the aggregator code, and the other problem was a default configuration setting that only kept information of the latest round in the aggregator database to minimize memory bloat, whereas the current and last round model are needed to generate the delta update. 

Would appreciate if you could check out the PR and let us know if you run into any other roadblocks. Cheers!

**Comment by alexey-gruzdev** [comment]
@Siyuqqq we've merged fix inside develop, so now it should work. Please double-check on your side!:)
