### ISSUE TITLE
Parallel execution for Python API 

### ISSUE THREAD

**Issue by alexey-gruzdev** [intel/openfl#37]
Python native API currently executes collaborators in a sequential way, however it could be done parallel, since their execution is independent.
```
for round_num in range(rounds_to_train):
        for col in plan.authorized_cols:

            collaborator = collaborators[col]
            model.set_data_loader(collaborator_dict[col].data_loader)

            if round_num != 0:
                model.rebuild_model(round_num, model_states[col])

            collaborator.run_simulation()

            model_states[col] = model.get_tensor_dict(with_opt_vars=True)
```

**Comment by itrushkin** [comment]
Protobuf objects can't be pickled into subprocesses so that PR also includes conversion to Python dictionaries in client-server interaction.

**Comment by tonyreina** [comment]
We should have a way to enable/disable this because if you are just working on a simulated federation for a single node, then you might exhaust resources by having many collaborators running concurrently on that node. I think that was the original use case for this. However, I agree it's good to have the parallel execution for most cases.

**Comment by alexey-gruzdev** [comment]
I would close this issue and corresponding PR #58 , since in general here we have to tackle problem of having multiple resources GPUs/CPUs (in parallel or sequential way) and with old API it's hard to do this in a right way. I believe with introduction of Director/Envoy this problem could be better solved on Envoys if they could explicitly say how many resources they have and we could utilize them from OpenFL.
