### ISSUE TITLE
Silent failures resulting from OOM errors

### ISSUE THREAD

**Issue by psfoley** [intel/openfl#456]
Some users have reported silent failures during training / validation likely resulting from out-of-memory errors. The failure in a low memory environment can be reproduced as follows:

```
# Install cgroup tools
apt install cgroup-tools
# Create cgroup
sudo cgcreate -t $USER:$GROUP -a $USER:$GROUP -g memory:/cgOpenFL
echo $(( 4096 * 1024 * 1024 )) | sudo tee /sys/fs/cgroup/memory/cgOpenFL/memory.limit_in_bytes #4 GB RAM
cgexec -g memory:cgOpenFL jupyter notebook
# Select and run [Medmnist 3D example](https://github.com/intel/openfl/blob/49f483d75545e16a9427be375ea91798d7e925dc/openfl-tutorials/interactive_api/PyTorch_MedMNIST_3D/workspace/Pytorch_MedMNIST_3D.ipynb)
``` 

Proposed solution:
- Catch [`MemoryError` exception](https://docs.python.org/2/library/exceptions.html#exceptions.MemoryError) in the Collaborator's `do_task` method at the [user-defined function invocation](https://github.com/intel/openfl/blob/develop/openfl/component/collaborator/collaborator.py#L255-L259)

**Comment by sun1lach** [comment]
@psfoley 

The collaborators `do_task` method doesn't capture the OOM error as the program terminates abruptly when the SIGKILL is triggered by the OS. Neither python `MemoryError` nor generic`Exception` catches this fatal error.

The `fx envoy` command terminates without propagating the exception/error levels higher.
The OOM error is captured in the kernel trace though but not at the user program level.


This 3D MedMNIST example
- **Fails** with the **PyTorch v1.3.1/v1.4.0** and CG memory restricted to **4GB**.
- **Succeeds** with **PyTorch v1.11.0** and CG memory restricted to **768MB**. (Tested with different configuration, even with 512MB).

Since the `training` and `validation` logic is implemented and registered as a task interface. No direct fail-safe way to restrict or optimize the execution of `training` and `validation` loop.

3D MedMNIST example execution and comparison was done on different PyTorch version with the clean virtual environment, I am convinced that its a runtime related issue and is corrected in the recent version of PyTorch.

I suggest to upgrade the PyTorch version 1.3.1 to 1.11.0 so that the memory utilization is better handled natively by PyTorch than us taking care of the MemoryError exceptions. 

We can do the PyTorch version upgrade, collaborate with the contributor and do a quick regression to conclude.
Do let me know your thoughts on this.

**Comment by psfoley** [comment]
@acharyasunil - thanks for the investigation on this. Seems like there probably is not a good way to provide additional information in our error message because it's a SIGKILL signal. I agree with updating the PyTorch version on those examples where it's possible.

In addition to the PyTorch version change, please add a note to the [OpenFL Troubleshooting documentation](https://openfl.readthedocs.io/en/latest/troubleshooting.html) about this type of OOM error, why no information is reported, and recommended remediation steps (i.e. what you've included in your previous comment) to guide other users.

**Comment by sun1lach** [comment]
PR #461 - Updated Documentation.

I will raise another PR in a while with the regression done on updated PyTorch version.

**Comment by sun1lach** [comment]
@psfoley 
PR #463 added relevant package versions in README.md that addresses this OOM issue.
