### ISSUE TITLE
Reducing the quantity of RAM used by director

### ISSUE THREAD

**Issue by CasellaJr** [intel/openfl#523]
I have tested different configurations of director/envoy. In particular, I am doing experiments with 2/4/8/10 envoys. I noted that when increasing the number of envoys connected to the director, the ram used (by director) increases exponentially. Basically, when using 2 or 4 envoys the ram used by director is fixed after some rounds and then does not increase, while when using 8 or 10 envoys, ram continues to increase. Can you study the way openfl uses ram? Because it is really expensive, both director and envoys side.

**Comment by psfoley** [comment]
Thanks for reporting this @CasellaJr! Just added this to our backlog.

A couple clarifying questions:
- Are the director and envoys on different nodes? A single node can be problematic for very large models 
- I would expect a linear increase due to collaborator tensors stored in the TensorDB. Have you adjusted the `aggregator.settings.db_store_rounds` parameter? Setting this to `1` (i.e. saving only the previous round's information) may make this slightly less expensive in the interim if there is a deeper issue here

**Comment by CasellaJr** [comment]
Hello Patrick @psfoley 

- Sure, I always use different nodes to run experiments.
- I did not change that parameter, `aggregator.settings.db_store_rounds`, I think It is equal to the default value. I am going to check what is.

**Comment by teoparvanov** [comment]
Closing this as the Interactive API has been deprecated.
